### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by ttPrivacy** [netease-youdao/EmotiVoice#74]
window的wsl2
cuda 11.6
torch==1.13.0+cu116 
torchvision==0.14.0+cu116 
torchaudio==0.13.0 
在运行官方案例的时候报错了
代码
`TEXT=data/inference/text
python inference_am_vocoder_joint.py \
--logdir prompt_tts_open_source_joint \
--config_folder config/joint \
--checkpoint g_00140000 \
--test_file $TEXT`
报错信息如下
`run!
Traceback (most recent call last):
  File "inference_am_vocoder_joint.py", line 156, in <module>
    main(args, config)
  File "inference_am_vocoder_joint.py", line 61, in main
    model_CKPT = torch.load(config.style_encoder_ckpt, map_location="cpu")
  File "/root/anaconda3/envs/EmotiVoice/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/EmotiVoice/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.`
请大佬解答，谢谢~

**Comment by ttPrivacy** [comment]
报错信息
(EmotiVoice) root@DESKTOP-O06UKC6:/home/tts/EmotiVoice-main# python inference_am_vocoder_joint.py --logdir prompt_tts_open_source_joint --config_folder config/joint --checkpoint g_00140000 --test_file data/inference/text
run!
Traceback (most recent call last):
  File "inference_am_vocoder_joint.py", line 156, in <module>
    main(args, config)
  File "inference_am_vocoder_joint.py", line 61, in main
    model_CKPT = torch.load(config.style_encoder_ckpt, map_location="cpu")
  File "/root/anaconda3/envs/EmotiVoice/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/EmotiVoice/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by ttPrivacy** [comment]
已解决，将[预训练模型](https://drive.google.com/drive/folders/1y6Xwj_GG9ulsAonca_unSGbJ4lxbNymM?usp=sharing)放到指定的目录就行了
