### ISSUE TITLE
datalist.jsonl

### ISSUE THREAD

**Issue by Ccj0221** [netease-youdao/EmotiVoice#76]
I am currently using the Montreal Forced Aligner (MFA) for an audio processing task, following the instructions in the documentation. However, I've encountered an issue when trying to proceed with subsequent tasks, as I cannot locate the datalist.jsonl file. The documentation mentions that if MFA has been run, this file should be renamed to datalist_mfa.jsonl. Nevertheless, in my environment, even after running MFA, the file seems to be missing.

I've double-checked the file path and naming to ensure there are no spelling errors. I've also made sure that the MFA run did not report any errors. However, it appears that the datalist_mfa.jsonl file has not been generated.

Could you please provide some assistance or guidance on resolving this issue and locating the datalist_mfa.jsonl file? I greatly appreciate your support.

~/EmotiVoice# python  mfa/step1_create_dataset.py \
> --data_dir data/DataBaker
Traceback (most recent call last):
  File "mfa/step1_create_dataset.py", line 41, in <module>
    main(args)
  File "mfa/step1_create_dataset.py", line 17, in main
    with jsonlines.open(f"{TEXT_DIR}/datalist.jsonl") as f1, \
  File "/root/miniconda3/envs/EmotiVoice/lib/python3.8/site-packages/jsonlines/jsonlines.py", line 643, in open
    fp = builtins.open(file, mode=mode + "t", encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/root/EmotiVoice/data/DataBaker/text/datalist.jsonl'

**Comment by syq163** [comment]
The file can be found in three locations: `data/DataBaker/text`, `data/DataBaker/train`, and `data/DataBaker/valid`.
