### ISSUE TITLE
您好，在demo推理阶段遇到了未知问题，想请教一下。

### ISSUE THREAD

**Issue by BookerShi** [netease-youdao/EmotiVoice#93]
您好，在demo推理阶段遇到了未知问题：

我的环境
torch==1.11.0
torchaudio==2.1.0
torchvision==0.16.0
transformers==4.26.1

Traceback (most recent call last):
  File "inference_am_vocoder_joint.py", line 156, in <module>
    main(args, config)
  File "inference_am_vocoder_joint.py", line 61, in main
    model_CKPT = torch.load(config.style_encoder_ckpt, map_location="cpu")
  File "/root/miniconda3/envs/EmotiVoice/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/EmotiVoice/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

请问一下作者这个可能是什么原因导致的谢谢

**Comment by syq163** [comment]
Have you prepared the pre-trained models as in our [wiki page](https://github.com/netease-youdao/EmotiVoice/wiki/Pretrained-models)?
